CREATE TABLE `property_matches` (
	`id` int AUTO_INCREMENT NOT NULL,
	`propertySubmissionId` int NOT NULL,
	`matchType` enum('property_listing','buyer_profile','investment_opportunity') NOT NULL,
	`title` varchar(255) NOT NULL,
	`description` text,
	`location` varchar(255) NOT NULL,
	`country` varchar(100),
	`price` int,
	`priceCurrency` varchar(10) DEFAULT 'USD',
	`propertyType` varchar(100),
	`bedrooms` int,
	`bathrooms` int,
	`squareFeet` int,
	`roi` decimal(5,2),
	`matchScore` decimal(5,2),
	`matchReason` text,
	`source` enum('zillow','redfin','realtor','lianjia','beike','airbnb','other') NOT NULL,
	`sourceUrl` varchar(500) NOT NULL,
	`contactName` varchar(255),
	`contactEmail` varchar(255),
	`contactPhone` varchar(20),
	`agentName` varchar(255),
	`agentPhone` varchar(20),
	`agentEmail` varchar(255),
	`images` json,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `property_matches_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `property_submissions` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`submissionType` enum('buyer_demand','seller_listing','investor_opportunity') NOT NULL,
	`transactionType` enum('buy','sell','rent','invest') NOT NULL,
	`description` text NOT NULL,
	`images` json,
	`budget` int,
	`budgetCurrency` varchar(10) DEFAULT 'USD',
	`location` varchar(255),
	`country` varchar(100),
	`propertyType` enum('residential','commercial','land','mixed'),
	`bedrooms` int,
	`bathrooms` int,
	`squareFeet` int,
	`expectedROI` decimal(5,2),
	`dealbreakers` json,
	`aiAnalysis` text,
	`aiTags` json,
	`matchProfile` json,
	`status` enum('pending','analyzing','completed','failed') DEFAULT 'pending',
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `property_submissions_id` PRIMARY KEY(`id`)
);
